In [90]:
import numpy as np
import pandas as pd

initial_df = pd.read_excel("data_clear.xlsx", parse_dates=["event_time"])

## Обрабатываем изначальный DataFrame, чтобы работать только с заданным промежутком времени

In [119]:
# 24.09.2020 - 28.02.2021
def set_time_intervals(start: str, end: str, df: pd.DataFrame) -> pd.DataFrame:
    start = list(map(int, start.split(".")))
    end = list(map(int, end.split(".")))
    start_ts = pd.Timestamp(day=start[0], month=start[1], year=start[2], tz="UTC")
    end_ts = pd.Timestamp(day=end[0], month=end[1], year=end[2], tz="UTC") + pd.Timedelta(days=1)
    time_mask = (start_ts <= df["event_time"]) & (end_ts > df["event_time"]) 
    return df[time_mask]


df = set_time_intervals("24.09.2020", "30.09.2020", initial_df)

## 1). Анализ пользователей, процентное соотношение всех событий к количеству сессий

In [138]:
from typing import Optional

class EventTypeAnalysis:
    def __init__(self, df: pd.DataFrame):
        self.LABEL = "Анализ совершённых событий пользователями"
        self.df: Optional[pd.DataFrame] = None
        self.total_sessions = len(df)

        self.views = df["has_view"].sum()
        self.carts = df["has_cart"].sum()
        self.purchases = df["has_purchase"].sum()

        self.view_percentage = round(self.views / self.total_sessions, 3)
        self.cart_percentage = round(self.carts / self.total_sessions, 3)
        self.purchases_percentage = round(self.purchases / self.total_sessions, 3)

    def make_analysis(self) -> pd.DataFrame:
        self.df = pd.DataFrame(
            columns=[self.LABEL],
            index=[
                "Колличество сессий",
                "Просмотры",
                "Добавлений в карзину",
                "Покупок",
                "% просмотров",
                "% добавлений в карзину",
                "% покупок"
                ])
        self.df.loc["Колличество сессий", self.LABEL] = self.total_sessions
        self.df.loc["Просмотры", self.LABEL] = self.views
        self.df.loc["Добавлений в карзину", self.LABEL] = self.carts
        self.df.loc["Покупок", self.LABEL] = self.purchases
        self.df.loc["% просмотров", self.LABEL] = self.view_percentage
        self.df.loc["% добавлений в карзину", self.LABEL] = self.cart_percentage
        self.df.loc["% покупок", self.LABEL] = self.purchases_percentage
        return self.df

event_type_df = df.groupby(["user_session"])["event_type"].apply(set).reset_index()
event_type_df["has_view"] = event_type_df["event_type"].apply(lambda x: "view" in x)
event_type_df["has_cart"] = event_type_df["event_type"].apply(lambda x: "cart" in x)
event_type_df["has_purchase"] = event_type_df["event_type"].apply(lambda x: "purchase" in x)

event_type_analysis = EventTypeAnalysis(event_type_df)
event_type_analysis.make_analysis()
# event_type_df[event_type_df["has_view"] == False]

                       Анализ совершённых событий пользователями
Колличество сессий                                         16990
Просмотры                                                  16935
Добавлений в карзину                                        1119
Покупок                                                      667
% просмотров                                               0.997
% добавлений в карзину                                     0.066
% покупок                                                  0.039

## 2). Анализ времени между событиями, сколько пользователь тратит времени между просмотром товара, добавлением в корзину и покупкой

In [140]:
df.sort_values(["user_session", "event_time"])

,event_time,event_type,product_id,category_code,brand,price,user_id,user_session
27192,2020-09-30 17:52:02+00:00,view,1675002,electronics.tablet,xiaomi,36646.14,1515915625509230080,000c34fa-991f-442a-8e07-8c472269bec6
9364,2020-09-26 18:59:06+00:00,view,3582066,computers.components.tv_tuner,d-color,2431.65,1515915625520059904,002DmERG1w
8955,2020-09-26 16:55:42+00:00,view,1247635,electronics.telephone,sirius,3645.30,1515915625519680000,009so5Mgnj
2481,2020-09-25 03:44:48+00:00,view,1756713,electronics.telephone,NaN,1822.65,1515915625519579904,00scna0OEj
2487,2020-09-25 03:46:21+00:00,view,1429384,electronics.telephone,NaN,696.00,1515915625519579904,00scna0OEj
...,...,...,...,...,...,...,...,...
22989,2020-09-29 19:55:01+00:00,view,275243,NaN,tp-link,709.92,1515915625520950016,zzrmGmDaIC
1130,2020-09-24 16:29:43+00:00,view,957592,electronics.tablet,samsung,1223.22,1515915625519480064,zzt9kKgXen
25849,2020-09-30 12:31:41+00:00,view,893196,computers.components.videocards,sapphire,18626.70,1515915625521110016,zztRHEozV0
25852,2020-09-30 12:32:12+00:00,view,877060,computers.components.videocards,msi,16294.23,1515915625521110016,zztRHEozV0
25853,2020-09-30 12:32:30+00:00,view,4100254,computers.components.videocards,asus,16294.23,1515915625521110016,zztRHEozV0

In [139]:
def func(df):
    print(df)
    print(type(df))
    print("--------------------------------")

df.sort_values(["user_session", "event_time"])
df.groupby("user_session").apply(func)

                     event_time event_type  product_id       category_code  \
27192 2020-09-30 17:52:02+00:00       view     1675002  electronics.tablet

        brand     price              user_id
27192  xiaomi  36646.14  1515915625509230080
<class 'pandas.DataFrame'>
--------------------------------
                    event_time event_type  product_id  \
9364 2020-09-26 18:59:06+00:00       view     3582066

                      category_code    brand    price              user_id
9364  computers.components.tv_tuner  d-color  2431.65  1515915625520059904
<class 'pandas.DataFrame'>
--------------------------------
                    event_time event_type  product_id          category_code  \
8955 2020-09-26 16:55:42+00:00       view     1247635  electronics.telephone

       brand   price              user_id
8955  sirius  3645.3  1515915625519680000
<class 'pandas.DataFrame'>
--------------------------------
                    event_time event_type  product_id          category_code  \
2481 2020-09-25 03:44:48+00:00       view     1756713  electronics.telephone
2487 2020-09-25 03:46:21+00:00       view     1429384  electronics.telephone
2488 2020-09-25 03:46:35+00:00       view     4013248  electronics.telephone

     brand    price              user_id
2481   NaN  1822.65  1515915625519579904
2487   NaN   696.00  1515915625519579904
2488   NaN  3755.79  1515915625519579904
<class 'pandas.DataFrame'>
--------------------------------
                     event_time event_type  product_id       category_code  \
18287 2020-09-28 20:56:59+00:00       view     1010878  electronics.tablet
18308 2020-09-28 21:05:07+00:00       view     1010878  electronics.tablet
18310 2020-09-28 21:05:32+00:00       view     1010878  electronics.tablet

        brand   price              user_id
18287  sirius  872.61  1515915625513989888
18308  sirius  872.61  1515915625513989888
18310  sirius  872.61  1515915625513989888
<class 'pandas.DataFrame'>
--------------------------------
                    event_time event_type  product_id category_code    brand  \
201  2020-09-24 12:43:41+00:00       view     4047111           NaN  samsung
202  2020-09-24 12:44:04+00:00       view     4047109           NaN  samsung
203  2020-09-24 12:44:28+00:00       cart     4047109           NaN  samsung
220  2020-09-24 12:48:35+00:00   purchase     4047109           NaN  samsung
2867 2020-09-25 06:16:14+00:00       view     4047111           NaN  samsung

        price              user_id
201   1881.81  1515915625470990080
202   2877.96  1515915625470990080
203   2877.96  1515915625470990080
220   2877.96  1515915625470990080
2867  1881.81  1515915625470990080
<class 'pandas.DataFrame'>
--------------------------------
                     event_time event_type  product_id          category_code  \
20375 2020-09-29 09:57:09+00:00       view     4013102  electronics.telephone

      brand    price              user_id
20375   NaN  1243.23  1515915625520780032
<class 'pandas.DataFrame'>
--------------------------------
                     event_time event_type  product_id         category_code  \
17427 2020-09-28 16:58:18+00:00       view     1695100  electronics.video.tv

      brand     price              user_id
17427   jvc  36085.86  1515915625483000064
<class 'pandas.DataFrame'>
--------------------------------
                     event_time event_type  product_id          category_code  \
2630  2020-09-25 04:52:05+00:00       view     1703545  electronics.telephone
20846 2020-09-29 11:33:07+00:00       view     1703545  electronics.telephone

        brand    price              user_id
2630   pitaka  4916.37  1515915625448169984
20846  pitaka  4916.37  1515915625448169984
<class 'pandas.DataFrame'>
--------------------------------
                     event_time event_type  product_id  \
19687 2020-09-29 07:53:55+00:00       view      406467

                  category_code    brand    price              user_id
19687  computers.network.router  tp-link  4764.12  1515915625520750080
<class 'pandas.DataFrame'>
--------------------------------
                   event_time event_type  product_id category_code brand  \
602 2020-09-24 14:08:51+00:00       view      668556           NaN   NaN

       price              user_id
602  5326.14  1515915625494309888
<class 'pandas.DataFrame'>
--------------------------------
                     event_time event_type  product_id category_code brand  \
15770 2020-09-28 10:51:18+00:00       view      411373           NaN   NaN

         price              user_id
15770  1243.23  1515915625520489984
<class 'pandas.DataFrame'>
--------------------------------
                     event_time event_type  product_id      category_code  \
22359 2020-09-29 17:30:27+00:00       view      324331  computers.desktop

      brand     price              user_id
22359   NaN  45143.43  1515915625520910080
<class 'pandas.DataFrame'>
--------------------------------
                     event_time event_type  product_id  \
27031 2020-09-30 17:17:45+00:00       view     4005380
27041 2020-09-30 17:20:06+00:00       view     4005380
27042 2020-09-30 17:20:12+00:00       view     4005380
27049 2020-09-30 17:21:03+00:00       view     3829633

                          category_code brand     price              user_id
27031  computers.components.motherboard   msi  20564.19  1515915625516250112
27041  computers.components.motherboard   msi  20564.19  1515915625516250112
27042  computers.components.motherboard   msi  20564.19  1515915625516250112
27049          computers.components.cpu   amd  35277.63  1515915625516250112
<class 'pandas.DataFrame'>
--------------------------------
                    event_time event_type  product_id  \
8466 2020-09-26 14:15:31+00:00       view      636448

                          category_code     brand    price  \
8466  appliances.kitchen.coffee_machine  scarlett  5288.73

                  user_id
8466  1515915625520000000
<class 'pandas.DataFrame'>
--------------------------------
                     event_time event_type  product_id  \
19807 2020-09-29 08:15:22+00:00       view     4012894

                       category_code     brand    price              user_id
19807  appliances.environment.vacuum  scarlett  8201.49  1515915625520750080
<class 'pandas.DataFrame'>
--------------------------------
                     event_time event_type  product_id  \
26614 2020-09-30 15:10:46+00:00       view     3828462

                     category_code        brand     price              user_id
26614  electronics.audio.headphone  steelseries  17515.71  1515915625521169920
<class 'pandas.DataFrame'>
--------------------------------
                    event_time event_type  product_id  \
9982 2020-09-27 00:49:29+00:00       view      753486

                   category_code   brand     price              user_id
9982  construction.tools.welding  wester  11007.24  1515915625520110080
<class 'pandas.DataFrame'>
--------------------------------
                     event_time event_type  product_id  \
13107 2020-09-27 18:18:50+00:00       view     4067425
13128 2020-09-27 18:25:39+00:00       view     4067425

                  category_code   brand    price              user_id
13107  construction.tools.drill  makita  5511.45  1515915625454520064
13128  construction.tools.drill  makita  5511.45  1515915625454520064
<class 'pandas.DataFrame'>
--------------------------------
                     event_time event_type  product_id  \
11818 2020-09-27 12:13:31+00:00       view     3829912

                       category_code   brand     price              user_id
11818  computers.peripherals.printer  pantum  10688.82  1515915625513659904
<class 'pandas.DataFrame'>
--------------------------------
                     event_time event_type  product_id  \
23166 2020-09-29 20:48:27+00:00       view     4079501
23220 2020-09-29 21:06:49+00:00       view      741173
23222 2020-09-29 21:07:53+00:00       view      629530
23228 2020-09-29 21:11:20+00:00       view     4013162
23232 2020-09-29 21:12:05+00:00       view     3642519

                 category_code      brand     price              user_id
23166  auto.accessories.player    pioneer  10066.77  1515915625495480064
23220  auto.accessories.player    pioneer  13795.59  1515915625495480064
23222  auto.accessories.player    pioneer   8845.29  1515915625495480064
23228       electronics.clocks  smarterra   2478.63  1515915625495480064
23232       electronics.clocks  smarterra   2085.39  1515915625495480064
<class 'pandas.DataFrame'>
--------------------------------
                     event_time event_type  product_id category_code brand  \
20177 2020-09-29 09:19:24+00:00       view      254548           NaN   NaN
20646 2020-09-29 10:54:39+00:00       view      215496           NaN   NaN
20649 2020-09-29 10:54:55+00:00       view      287526           NaN   NaN
21714 2020-09-29 14:55:45+00:00       view      287525           NaN   NaN

         price              user_id
20177   448.92  1515915625520770048
20646  1092.72  1515915625520770048
20649   930.90  1515915625520770048
21714   813.45  1515915625520770048
<class 'pandas.DataFrame'>
--------------------------------
                    event_time event_type  product_id category_code     brand  \
3319 2020-09-25 07:54:13+00:00       view      827365           NaN  mechanic
3899 2020-09-25 09:52:00+00:00       view      827365           NaN  mechanic

        price              user_id
3319  1081.41  1515915625519630080
3899  1081.41  1515915625519630080
<class 'pandas.DataFrame'>
--------------------------------
                     event_time event_type  product_id category_code brand  \
20794 2020-09-29 11:21:45+00:00       view      350103           NaN  sony

         price              user_id
20794  5482.74  1515915625520809984
<class 'pandas.DataFrame'>
--------------------------------
                   event_time event_type  product_id  \
476 2020-09-24 13:42:18+00:00       view     3506322
479 2020-09-24 13:42:34+00:00       cart     3506322
485 2020-09-24 13:43:30+00:00   purchase     3506322

                     category_code   brand    price              user_id
476  computers.components.tv_tuner  perfeo  1695.63  1515915625358479872
479  computers.components.tv_tuner  perfeo  1695.63  1515915625358479872
485  computers.components.tv_tuner  perfeo  1695.63  1515915625358479872
<class 'pandas.DataFrame'>
--------------------------------
                     event_time event_type  product_id category_code  brand  \
16860 2020-09-28 14:47:18+00:00       view      421649           NaN  faura

          price              user_id
16860  16892.79  1515915625459259904
<class 'pandas.DataFrame'>
--------------------------------
                     event_time event_type  product_id category_code    brand  \
13195 2020-09-27 18:41:04+00:00       view     1044370           NaN  thermos

         price              user_id
13195  5522.76  1515915625520320000
<class 'pandas.DataFrame'>
--------------------------------
                     event_time event_type  product_id category_code brand  \
15529 2020-09-28 10:06:22+00:00       view      335814           NaN   NaN

         price              user_id
15529  1311.96  1515915625520470016
<class 'pandas.DataFrame'>
--------------------------------
                    event_time event_type  product_id  \
1754 2020-09-24 19:24:34+00:00       view      387951

                        category_code brand    price              user_id
1754  computers.components.videocards  asus  4435.26  1515915625519520000
<class 'pandas.DataFrame'>
--------------------------------
                   event_time event_type  product_id category_code brand  \
276 2020-09-24 12:58:24+00:00       view       50684           NaN   NaN

       price              user_id
276  2278.53  1515915625516049920
<class 'pandas.DataFrame'>
--------------------------------
                     event_time event_type  product_id  \
22212 2020-09-29 16:51:03+00:00       view      846904

                    category_code   brand     price              user_id
22212  computers.peripherals.wifi  huawei  12967.35  1515915625362070016
<class 'pandas.DataFrame'>
--------------------------------
                    event_time event_type  product_id       category_code  \
6860 2020-09-26 05:10:04+00:00       view     1428320  electronics.tablet
6875 2020-09-26 05:15:45+00:00       cart     1428320  electronics.tablet

        brand    price              user_id
6860  samsung  1615.59  1515915625519879936
6875  samsung  1615.59  1515915625519879936
<class 'pandas.DataFrame'>
--------------------------------
                    event_time event_type  product_id          category_code  \
8979 2020-09-26 17:00:41+00:00       view     3829475  electronics.telephone

     brand    price              user_id
8979   NaN  3769.71  1515915625461680128
<class 'pandas.DataFrame'>
--------------------------------
                     event_time event_type  product_id        category_code  \
26281 2020-09-30 13:58:11+00:00       view      603240  stationery.cartrige
26285 2020-09-30 13:58:46+00:00       view      603240  stationery.cartrige

       brand   price              user_id
26281  sharp  8325.9  1515915625521159936
26285  sharp  8325.9  1515915625521159936
<class 'pandas.DataFrame'>
--------------------------------
                    event_time event_type  product_id category_code    brand  \
1057 2020-09-24 16:10:14+00:00       view      812684           NaN  sandisk

         price              user_id
1057  11522.28  1515915625519470080
<class 'pandas.DataFrame'>
--------------------------------
                     event_time event_type  product_id       category_code  \
20803 2020-09-29 11:24:03+00:00       view     3506612  electronics.tablet

       brand    price              user_id
20803  arian  4101.18  1515915625520809984
<class 'pandas.DataFrame'>
--------------------------------
                     event_time event_type  product_id  \
21387 2020-09-29 13:30:49+00:00       view      180228
21395 2020-09-29 13:32:00+00:00       cart      180228
21403 2020-09-29 13:33:28+00:00   purchase      180228

                     category_code   brand   price              user_id
21387  computers.components.cooler  zalman  968.31  1515915625514959872
21395  computers.components.cooler  zalman  968.31  1515915625514959872
21403  computers.components.cooler  zalman  968.31  1515915625514959872
<class 'pandas.DataFrame'>
--------------------------------
                     event_time event_type  product_id  \
23947 2020-09-30 05:32:36+00:00       view     1756469
23969 2020-09-30 05:40:34+00:00       view     1756469

                           category_code   brand   price              user_id
23947  appliances.environment.air_heater  zencha  1966.2  1515915625521019904
23969  appliances.environment.air_heater  zencha  1966.2  1515915625521019904
<class 'pandas.DataFrame'>
--------------------------------
                     event_time event_type  product_id  \
26951 2020-09-30 16:58:38+00:00       view     4101475

                 category_code brand    price              user_id
26951  auto.accessories.player   jvc  5316.57  1515915625469400064
<class 'pandas.DataFrame'>
--------------------------------
                     event_time event_type  product_id  \
12377 2020-09-27 15:03:25+00:00       view       89974
12382 2020-09-27 15:03:54+00:00       view       89974
12384 2020-09-27 15:04:08+00:00       view       89974

                category_code brand    price              user_id
12377  construction.tools.saw  bort  5648.04  1515915625520270080
12382  construction.tools.saw  bort  5648.04  1515915625520270080
12384  construction.tools.saw  bort  5648.04  1515915625520270080
<class 'pandas.DataFrame'>
--------------------------------
                    event_time event_type  product_id  \
1123 2020-09-24 16:27:49+00:00       view      809948
1147 2020-09-24 16:32:46+00:00       view      809948

                         category_code brand    price              user_id
1123  computers.components.motherboard  asus  5609.76  1515915625518099968
1147  computers.components.motherboard  asus  5609.76  1515915625518099968
<class 'pandas.DataFrame'>
--------------------------------
                     event_time event_type  product_id category_code  brand  \
23635 2020-09-30 02:36:11+00:00       view     3627430           NaN  lexar

         price              user_id
23635  2485.59  1515915625509720064
<class 'pandas.DataFrame'>
--------------------------------
                     event_time event_type  product_id  \
11388 2020-09-27 10:24:19+00:00       view     3791351
11463 2020-09-27 10:37:54+00:00       view     1578301
11494 2020-09-27 10:44:54+00:00       view     1578301
11495 2020-09-27 10:45:18+00:00       view     3791351

                          category_code     brand     price  \
11388          computers.components.cpu       amd  17773.23
11463  computers.components.motherboard  gigabyte   6704.22
11494  computers.components.motherboard  gigabyte   6704.22
11495          computers.components.cpu       amd  17773.23

                   user_id
11388  1515915625520199936
11463  1515915625520199936
11494  1515915625520199936
11495  1515915625520199936
<class 'pandas.DataFrame'>
--------------------------------
                     event_time event_type  product_id        category_code  \
11502 2020-09-27 10:46:32+00:00       view       66108  stationery.cartrige
11504 2020-09-27 10:46:35+00:00       view       66108  stationery.cartrige

        brand    price              user_id
11502  cactus  2046.24  1515915625512169984
11504  cactus  2046.24  1515915625512169984
<class 'pandas.DataFrame'>
--------------------------------
                     event_time event_type  product_id category_code brand  \
27540 2020-09-30 19:22:11+00:00       view     1715712           NaN   NaN

         price              user_id
27540  2762.25  1515915625521240064
<class 'pandas.DataFrame'>
--------------------------------
                    event_time event_type  product_id  \
5219 2020-09-25 15:04:18+00:00       view      788861

                 category_code   brand    price              user_id
5219  construction.tools.drill  p.i.t.  5171.28  1515915625384229888
<class 'pandas.DataFrame'>
--------------------------------
                    event_time event_type  product_id category_code  \
9331 2020-09-26 18:49:28+00:00       view        1804           NaN

          brand    price              user_id
9331  transcend  2332.47  1515915625520059904
<class 'pandas.DataFrame'>
--------------------------------
                     event_time event_type  product_id category_code  brand  \
17285 2020-09-28 16:26:19+00:00       view     1263563           NaN  fubag

         price              user_id
17285  5055.57  1515915625520580096
<class 'pandas.DataFrame'>
--------------------------------
                    event_time event_type  product_id  \
7095 2020-09-26 06:40:37+00:00       view     1022292
7249 2020-09-26 07:34:18+00:00       view      883910
7250 2020-09-26 07:35:14+00:00       view      883911
7265 2020-09-26 07:40:13+00:00       view     1022292
7268 2020-09-26 07:41:31+00:00       view     1022292
7269 2020-09-26 07:41:53+00:00       view      895682
7274 2020-09-26 07:43:57+00:00       view     1503537

                      category_code    brand    price              user_id
7095  appliances.environment.vacuum  pitatel  5330.49  1515915625519889920
7249  appliances.environment.vacuum    topon  3438.24  1515915625519889920
7250  appliances.environment.vacuum    topon  3632.25  1515915625519889920
7265  appliances.environment.vacuum  pitatel  5330.49  1515915625519889920
7268  appliances.environment.vacuum  pitatel  5330.49  1515915625519889920
7269  appliances.environment.vacuum  pitatel  3921.96  1515915625519889920

KeyboardInterrupt: